server:
  port: 8000

spring:
  security:
    user:
      name: sa
      password: sa
  jmx:
    enabled: true
  datasource:
    url: jdbc:mysql://${DATABASE_HOST:localhost}:${DATABASE_PORT:3600}/${DATABASE_NAME:calendar_db}?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: ${DATABASE_USER:user}
    password: ${DATABASE_PASSWORD:password}
    driverClassName: com.mysql.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    defer-datasource-initialization: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        generate_statistics: true
        jdbc:
          batch_size: 50
          batch_versioned_data: true
        order_inserts: true
        order_update: true
        format_sql: true
        show_sql: true
  h2:
    console:
      enabled: true
      path: /h2-console
  quartz:
    properties:
      org.quartz.threadPool:
        threadCount: 2